#### **```NumPy```**

In [1]:
import numpy as np

In [2]:
twoD_array = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(twoD_array)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
twoD_array.shape

(2, 4)

In [4]:
# check dimensions of an array
print(twoD_array.ndim)

2


In [5]:
# number of elements in an array
print(twoD_array.size)

8


In [6]:
# check data type
print(twoD_array.dtype)

int32


```Convert 2D or multidimensional array into 1D array```

In [7]:
multi_array = np.random.randint(5, 10, (3, 2))
print(multi_array)

# convert into 1D array
single_D_array = multi_array.flatten()
print(single_D_array)

[[6 5]
 [9 8]
 [5 7]]
[6 5 9 8 5 7]


Initial placeholders

In [8]:
# array initialized with all zeros
x = np.zeros((4, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
# array initialized with a particular value
y = np.full((4, 5), 33)
print(y)

[[33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]]


In [10]:
# Identity matrix: matrix that have an equal number of rows and columns 
z = np.eye(6)
print(z)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [11]:
# array with random floating point values
randMatrix1 = np.random.random((5, 6))
print(randMatrix1)

[[0.0969918  0.36991976 0.11366062 0.85149609 0.437635   0.77721195]
 [0.01418297 0.17400997 0.65565719 0.75101469 0.64174335 0.88932491]
 [0.99883322 0.61088151 0.89999378 0.85691552 0.75588696 0.9349958 ]
 [0.41246634 0.23117228 0.79649959 0.60363438 0.32055762 0.25355656]
 [0.79484845 0.21495588 0.18141211 0.90600954 0.30683738 0.85375816]]


In [12]:
# array with random integer values within a specific range
randMatrix2 = np.random.randint(100, 200, (4, 5))
print(randMatrix2)

[[114 132 133 157 111]
 [133 125 178 173 121]
 [155 103 144 174 119]
 [131 176 165 132 111]]


In [13]:
# array with evenly spaced values -> number of values required
evenlySpacedArray = np.linspace(10, 30, 11)
print(evenlySpacedArray)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [14]:
# array with evenly spaced values -> specifying the number of steps
sequenceArray = np.arange(10, 30, 2)
print(sequenceArray)

[10 12 14 16 18 20 22 24 26 28]


In [15]:
# convert regular python list into numpy array
list2 = [10, 20, 30, 40, 50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

#### ```Mathematical operations```

In [16]:
list1 = np.array([1, 2, 3, 4])
list2 = np.array([10, 20, 30, 40])

# concatenation
print(list1 + list2)
print(list1 * list2)

[11 22 33 44]
[ 10  40  90 160]


In [17]:
list2D_1 = np.array([(1, 2, 3), (4, 5, 6)])
list2D_2 = np.array([(10, 20, 30), (40, 50, 60)])
print(list2D_1 + list2D_2)
print(list2D_1 - list2D_2)
print(list2D_1 * list2D_2)
print(list2D_1 / list2D_2)

[[11 22 33]
 [44 55 66]]
[[ -9 -18 -27]
 [-36 -45 -54]]
[[ 10  40  90]
 [160 250 360]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [18]:
a = np.random.randint(10, 20, (3, 3))
b = np.random.randint(30, 40, (3, 3))

In [19]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[55 53 47]
 [42 41 48]
 [54 48 52]]
[[-23 -15 -25]
 [-18 -21 -12]
 [-20 -16 -26]]
[[624 646 396]
 [360 310 540]
 [629 512 507]]
[[0.41025641 0.55882353 0.30555556]
 [0.4        0.32258065 0.6       ]
 [0.45945946 0.5        0.33333333]]


In [20]:
# Transpose matrix: A matrix that obtained by interchanging the rows and columns.
matrix = np.random.randint(10, 30, (3, 2))
print(matrix)

# initializing matrix as transpose matrix
transpose_mat = matrix.T
print(transpose_mat)

# converting the existing matrix into a transpose matrix
matrix = matrix.T
print(matrix)

[[26 27]
 [23 27]
 [26 11]]
[[26 23 26]
 [27 27 11]]
[[26 23 26]
 [27 27 11]]


```Reshaping an array```

In [21]:
a = np.random.randint(5, 15, (4, 3))
print(a)
b = a.reshape(3, 4)
print(b)

[[ 7 10  7]
 [ 8 12 12]
 [ 9  7 13]
 [ 6 14  8]]
[[ 7 10  7  8]
 [12 12  9  7]
 [13  6 14  8]]
