In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1, 12, 2)
arr1

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
arr2 = np.linspace(0, 10, 20)
arr2

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
arr3 = np.random.rand(10)
arr3

array([0.74023815, 0.36591631, 0.3739556 , 0.08704778, 0.47016179,
       0.31728135, 0.96376178, 0.36863752, 0.95405568, 0.40958904])

In [14]:
# Creating an array with all same values 

arr4 = np.full((5, 5), 12)
arr4

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [15]:
# Creating array with repeating values

arr5 = np.repeat([1, 2, 3], 5) # each value of array [1, 2, 3] will be repeated for 5 times
arr5

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [17]:
# identity matrix 

idm = np.identity(4)
idm

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
arr6 = np.random.rand(4, 3)
arr6

array([[0.3738619 , 0.31901482, 0.49441767],
       [0.14220253, 0.9825523 , 0.85824693],
       [0.62576382, 0.37609934, 0.33181437],
       [0.56028185, 0.4131148 , 0.37900257]])

In [25]:
# column wise sum 
print(np.sum(arr6, axis=0))

# row wise sum 
print(np.sum(arr6, axis=1))

[1.7021101  2.09078126 2.06348155]
[1.18729439 1.98300177 1.33367753 1.35239922]


In [ ]:
# delete multiple np array elements
arr7 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr7)

arr7 = np.delete(arr7, [1, 5])
print(arr7)

[1 2 3 4 5 6 7 8 9]
[1 3 4 5 7 8 9]
