In [104]:
import numpy as np
import tensorflow as tf

var1 = tf.Variable([1, 2, 3])
var2 = tf.constant([3, 4, 5])

print(var1.numpy())
print(var2.numpy())

[1 2 3]
[3 4 5]


### Perceptron Implementation

In [105]:
w = tf.Variable([.2])  # initial weight, it can be anything
b = tf.Variable([-.2])
x = tf.Variable(tf.zeros(shape=(1, 4)))
y = tf.constant([0, -1., -2., -3.])

w.numpy(), b.numpy(), x.numpy(), y.numpy()

(array([0.2], dtype=float32),
 array([-0.2], dtype=float32),
 array([[0., 0., 0., 0.]], dtype=float32),
 array([ 0., -1., -2., -3.], dtype=float32))

In [106]:
x.assign([[1, 2, 3, 4]])
linear_model = w * x + b

In [107]:
linear_model.numpy()

array([[0.        , 0.2       , 0.40000004, 0.6       ]], dtype=float32)

Loss function

In [108]:
squared_deltas = tf.square(linear_model - y)
loss = tf.reduce_sum(squared_deltas)

In [109]:
loss.numpy()

20.16