In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Tensors

Tensors can run on GPU's

In [2]:
# Scalar: A scalar contains a single element
# Scalar has no dimension
scalar = torch.tensor(7)
# To seek only the value itself, this method only available for scalars or single element tensors
scalar.item()
scalar, scalar.ndim, scalar.shape, scalar.size()

(tensor(7), 0, torch.Size([]), torch.Size([]))

In [3]:
# Vector: Also know as 1D array that contains multiple scalars
vector = torch.tensor([10, 20])
vector, vector.ndim, vector.size(), vector.shape

(tensor([10, 20]), 1, torch.Size([2]), torch.Size([2]))

In [4]:
# Matrix

MATRIX = torch.tensor([
    [10, 20],
    [30, 40]
])

MATRIX, MATRIX.size(), MATRIX.ndim, MATRIX.shape

(tensor([[10, 20],
         [30, 40]]),
 torch.Size([2, 2]),
 2,
 torch.Size([2, 2]))

In [5]:
# Any dimension we usually see above 2 is more precisely said to be TENSOR's

# This is a 3D tensor
TENSOR = torch.tensor([
    # 1st 2D matrix
    [
        [1, 2],
        [3, 4]
    ],

    # 2nd 2D matrix
    [
        [10, 20],
        [30, 40]
    ]
])

TENSOR

tensor([[[ 1,  2],
         [ 3,  4]],

        [[10, 20],
         [30, 40]]])

In [6]:
TENSOR.shape

torch.Size([2, 2, 2])

**Random Tensors**

Randoms tensors are significantly important due to the reason that, neural networks particularly initialized with random numbers

In [7]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.1129, 0.6804, 0.7794, 0.1527],
         [0.4106, 0.4181, 0.8683, 0.0317],
         [0.5009, 0.1552, 0.3120, 0.9240]],

        [[0.1028, 0.8084, 0.5906, 0.4335],
         [0.4643, 0.3568, 0.4046, 0.4182],
         [0.7258, 0.0236, 0.1629, 0.3447]]])

In [8]:
random_tensor_2 = torch.rand(2, 3, 2, 3)
random_tensor_2

tensor([[[[0.3201, 0.2286, 0.1749],
          [0.0721, 0.8235, 0.5941]],

         [[0.3139, 0.9846, 0.0847],
          [0.7678, 0.7187, 0.9053]],

         [[0.5365, 0.2404, 0.5392],
          [0.5483, 0.8808, 0.1918]]],


        [[[0.3177, 0.1291, 0.9499],
          [0.8023, 0.3882, 0.7777]],

         [[0.0749, 0.5750, 0.4761],
          [0.2153, 0.0525, 0.5056]],

         [[0.9538, 0.7666, 0.3170],
          [0.1199, 0.2963, 0.9482]]]])

In [9]:
random_tensor.ndim, random_tensor_2.ndim

(3, 4)

Image

In [10]:
random_img_tensor = torch.rand(size=(3, 224, 224))
random_img_tensor

tensor([[[0.0135, 0.6641, 0.6462,  ..., 0.6198, 0.2514, 0.3441],
         [0.0343, 0.3538, 0.4405,  ..., 0.1871, 0.8920, 0.3115],
         [0.7858, 0.2336, 0.1108,  ..., 0.6833, 0.4430, 0.7807],
         ...,
         [0.0893, 0.8836, 0.7627,  ..., 0.0734, 0.7268, 0.7405],
         [0.9240, 0.2414, 0.0320,  ..., 0.5044, 0.5470, 0.6569],
         [0.1668, 0.3606, 0.9842,  ..., 0.0420, 0.8759, 0.0703]],

        [[0.7587, 0.2031, 0.7244,  ..., 0.0071, 0.3521, 0.0648],
         [0.7831, 0.6497, 0.7138,  ..., 0.7904, 0.7305, 0.3673],
         [0.9978, 0.9804, 0.2696,  ..., 0.5744, 0.5262, 0.9943],
         ...,
         [0.3363, 0.4475, 0.7149,  ..., 0.4903, 0.1987, 0.6196],
         [0.5619, 0.1725, 0.8593,  ..., 0.4862, 0.4343, 0.7065],
         [0.9553, 0.7564, 0.1056,  ..., 0.8128, 0.4019, 0.4410]],

        [[0.2615, 0.4576, 0.5571,  ..., 0.3961, 0.8304, 0.0708],
         [0.6399, 0.7469, 0.5596,  ..., 0.6400, 0.3516, 0.5542],
         [0.5444, 0.8105, 0.9839,  ..., 0.2628, 0.5843, 0.

In [11]:
zero_tensor = torch.zeros(size=(5, 5))
zero_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [12]:
tensor_all_ones = torch.ones(size=(5, 5))
tensor_all_ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Range Tensors

In [13]:
one_to_100 = torch.arange(1, 101)
one_to_100

tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100])

In [14]:
ten_table = torch.arange(start=10, end=101, step=10)
ten_table

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [15]:
for x in ten_table:
  print(x.item(), end=" ")

10 20 30 40 50 60 70 80 90 100 

### Tensor data types

Using tensors without knowing the correct use of parameters, it may lead to errors. Here are the reasons:
1. Tensors are not in the right datatypes.
2. Tensors shapes are not similar
3. Tensors are not in the right device.

In [16]:
float_32_tensor = torch.tensor([5, 7, 9],
                               dtype=torch.float32,
                               device='cpu',
                               requires_grad=False)
float_32_tensor

tensor([5., 7., 9.])

In [17]:
random_tensor_3 = torch.rand(size=(3, 5))
print(random_tensor_3)

tensor([[0.4976, 0.1885, 0.2181, 0.5201, 0.4287],
        [0.8542, 0.7225, 0.0500, 0.8195, 0.8994],
        [0.8755, 0.0435, 0.9354, 0.8825, 0.2487]])
