Question 1: Create a 2D array of shape (3, 4) filled with random values.

In [14]:
# Using plain python

import random 
import numpy as np

arr_2d_py = []

for i in range(1, 4):
    temp_arr = [random.randint(1, 100) for i in range(1, 5)]
    arr_2d_py.append(temp_arr)

print(arr_2d_py)

# Using numpy 

arr_2d_num = np.random.rand(3, 4) * 100
print(arr_2d_num)

[[14, 40, 63, 48], [18, 7, 77, 68], [13, 88, 67, 63]]
[[50.68047937 86.7472028  76.48374155 26.09375013]
 [83.26144563 55.85179291  3.05085289 16.3887896 ]
 [83.15432358 80.0619718  23.82831217 19.32312762]]


 Question 2. Array Operations:

(a)Add two arrays element-wise.
(b)Multiply two arrays element-wise.
(c)Calculate the dot product of two arrays.
(d)Transpose a matrix.
(e)Find the inverse of a matrix.

In [53]:
matrix_one = (np.random.rand(4, 4) * 10).astype(int)
matrix_two = (np.random.rand(4, 4) * 10).astype(int)
arr_1d_one = (np.random.rand(10) * 10).astype(int)
arr_1d_two = (np.random.rand(10) * 10).astype(int)

print(matrix_one, end="\n\n")
print(matrix_two, end="\n\n")
print(arr_1d_one, end="\n\n")
print(arr_1d_two)

[[3 2 0 3]
 [4 8 6 5]
 [5 5 7 7]
 [0 5 4 5]]

[[7 4 5 2]
 [6 9 8 7]
 [1 1 0 4]
 [3 8 3 9]]

[0 8 0 7 3 7 1 9 1 8]

[1 0 9 8 3 1 9 5 1 3]


In [54]:
# Addition operation of 2D array
matrix_addition = matrix_one + matrix_two
print(matrix_addition, end="\n\n")

# 1D array addition
arr_addition = arr_1d_one + arr_1d_two
print(arr_addition)

[[10  6  5  5]
 [10 17 14 12]
 [ 6  6  7 11]
 [ 3 13  7 14]]

[ 1  8  9 15  6  8 10 14  2 11]


In [55]:
# Multiplication operation

matrix_multiplication_element_wise = matrix_one * matrix_two
print(matrix_multiplication_element_wise, end="\n\n")

# multiplication 1d array, I've now used the numpy method
multiplication_1d_array = np.multiply(arr_1d_one, arr_1d_two)
print(multiplication_1d_array)

[[21  8  0  6]
 [24 72 48 35]
 [ 5  5  0 28]
 [ 0 40 12 45]]

[ 0  0  0 56  9  7  9 45  1 24]


In [38]:
# Dot product of two matrices

matrix_dot_product = np.dot(matrix_one, matrix_two)
matrix_dot_product

array([[123, 116,  56,  36],
       [160, 152,  93,  80],
       [100,  97,  75,  49],
       [ 91,  88,  50,  44]])

In [42]:
# Transposing the first matrix 

transposed_matrix_one = np.transpose(matrix_one)
# print(matrix_one, end="\n\n")
print(transposed_matrix_one)

[[6 6 9 0]
 [4 0 5 2]
 [9 1 6 5]
 [2 1 8 1]]

[[6 4 9 2]
 [6 0 1 1]
 [9 5 6 8]
 [0 2 5 1]]


In [43]:
# inverse of second matrix 

inversed_matrix_two = np.linalg.inv(matrix_two)
inversed_matrix_two

array([[ 0.21428571, -0.07142857, -0.07142857,  0.07142857],
       [-0.06593407,  0.17582418,  0.0989011 , -0.17582418],
       [-0.08791209, -0.0989011 ,  0.13186813,  0.0989011 ],
       [-0.27884615,  0.20192308, -0.14423077,  0.04807692]])

Question 3. Array Indexing and Slicing:

(a)Extract the first row from a 2D array.
(b)Extract the last column from a 2D array.
(c)Create a new array from a slice of an existing array.
(d)Modify elements in an array using indexing.

In [65]:
# a
print(matrix_one, end="\n\n")
first_row = matrix_one[:1]
print(first_row)

[[3 2 0 3]
 [4 8 6 5]
 [5 5 7 7]
 [0 5 4 5]]

[[3 2 0 3]]


In [67]:
# b
n = len(matrix_one)
last_column = matrix_one[:n, n-1: n]
last_column

array([[3],
       [5],
       [7],
       [5]])

In [70]:
# c 
print(arr_1d_one)
new_arr = arr_1d_one[:5]
print(new_arr)

[0 8 0 7 3 7 1 9 1 8]
[0 8 0 7 3]


In [72]:
# d 
new_arr[0] = 10
new_arr[1] = 20

print(new_arr)

[10 20  0  7  3]


Question 4: I.	Write a Python program to calculate the arc length of an angle.

          arc_length = (pi*diameter) * (angle/360)


In [75]:
import math

diameter = float(input("Enter diameter value: "))
angle = float(input("Enter angle value: "))
arc_length = ((math.pi * diameter) * (angle/360))
print(arc_length)

2.617993877991494


Question 5: Repeatedly ask the user to enter game scores in a format like team1 score1 - team2 score2. Store
this information in a dictionary where the keys are the team names and the values are lists of
the form [wins, losses].

In [4]:
win_loss_dict = {
    "Team 1": [0, 0],
    "Team 2": [0, 0]
}
match_cnt = int(input("Enter total number of matches both team will play: "))

for i in range(1, match_cnt + 1):
    print(f"Game no. {i}")
    t1_score = int(input("Team 1 score: "))
    t2_score = int(input("Team 2 score: "))

    if t1_score > t2_score:
        win_loss_dict["Team 1"][0] += 1
        win_loss_dict["Team 2"][1] += 1
    elif t2_score > t1_score:
        win_loss_dict["Team 2"][0] += 1
        win_loss_dict["Team 1"][1] += 1

print(f"Team 1 total match won: {win_loss_dict['Team 1'][0]} and loss: {win_loss_dict['Team 1'][1]}")
print(f"Team 2 total match won: {win_loss_dict['Team 2'][0]} and loss: {win_loss_dict['Team 2'][1]}")

Game no. 1
Game no. 2
Game no. 3
Game no. 4
Game no. 5
Team 1 total match won: 2 and loss: 3
Team 2 total match won: 3 and loss: 2
