In [1]:
import tensorflow as tf
print(tf.__version__)

2.16.1


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [3]:
# checking dimension of the tensor
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10, 100.55])
vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 10.  , 100.55], dtype=float32)>

In [5]:
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([[10, 100], [1000, 100000]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[    10,    100],
       [  1000, 100000]])>

In [7]:
float_dtype_matrix_1 = tf.constant([[10.55, 20.4324],
                                    [30, 40.4324]], dtype=tf.float32)

float_dtype_matrix_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.55  , 20.4324],
       [30.    , 40.4324]], dtype=float32)>

In [8]:

# you can't directly typecast a float type into an integer type
# to do so, you have to take a secondary matrix help

int_dtype_matrix_1 = tf.cast(float_dtype_matrix_1, dtype=tf.int32)
int_dtype_matrix_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [9]:
int_dtype_matrix_1.ndim

2

In [10]:
# Tensor
tensor = tf.constant([
    [[1, 2, 3, 4], [5, 6, 7, 8]],
    [[10, 11, 12, 13], [14, 15, 16, 17]],
    [[100, 200, 300, 99], [400, 500, 600, 77]]
])

tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8]],

       [[ 10,  11,  12,  13],
        [ 14,  15,  16,  17]],

       [[100, 200, 300,  99],
        [400, 500, 600,  77]]])>

`tf.Variable` is a changeable tensor or mutable, that can be redefined later on. Whereas, `tf.constant` creates immutable tensors.


In [11]:
# Creating tensor using tf.Variable

changeable_tensor = tf.Variable([10, 20, 30, 40])
unchangeable_tensor = tf.constant([10, 20])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10, 20, 30, 40])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20])>)

In [12]:
# To change a value use the method .assign()

changeable_tensor[1].assign(changeable_tensor[1] * 10)
changeable_tensor, tf.size(changeable_tensor)

(<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 10, 200,  30,  40])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

Creating random tensors


In [13]:
random_1 = tf.random.Generator.from_seed(20)
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(20)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2    

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ],
        [ 0.86754173, -0.19625713],
        [-1.322665  , -0.02279496]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.88051325, -1.6833194 ],
        [ 0.86754173, -0.19625713],
        [-1.322665  , -0.02279496]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [14]:
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]])>

In [15]:
# Global random seed
tf.random.set_seed(42)

# operational level seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

Creating a tensor with value 1

In [16]:
# Syntax 1 
tf.ones([3, 4], tf.int32)

# Syntax 2
tf.ones(shape=(3, 4), dtype=tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])>

In [17]:
# Syntax 1
tf.zeros([3, 4], tf.int32)

# Syntax 2 
tf.zeros(shape=(3, 5), dtype=tf.int32)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

## Turn NumPy arrays into tensors

**Difference**: Tensors can run on GPU's for faster processing whereas NumPy arrays conventional arrays

In [37]:
import numpy as np
numpy_array = np.arange(1, 51).reshape(5, 10)
numpy_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [38]:
tf_tensor_1 = tf.Variable(numpy_array)
tf_tensor_1

<tf.Variable 'Variable:0' shape=(5, 10) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])>

In [40]:
tf_tensor_2 = tf.constant(numpy_array, shape=(5, 2, 5))
tf_tensor_2

<tf.Tensor: shape=(5, 2, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]]])>

### Methods

- Shape 
- Rank 
- Axis or dimension
- Size

In [43]:
# Creating a rank 4 tensor
# or we can say it is a 4D tensor
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])

print(rank_4_tensor)

tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]], shape=(2, 3, 4, 5), dtype=float32)


In [44]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [47]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor), rank_4_tensor.dtype

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 tf.float32)

In [48]:
print(f"Total number of elements in the tensor: {tf.size(rank_4_tensor).numpy()}")

Total number of elements in the tensor: 120
