In [6]:
import numpy as np

# 1. ReLU - Rectified Linear Unit

In [7]:
def relu(x):
    return np.maximum(0, x)

print(relu(10))
print(relu(-10))
print(relu(np.array([10, 20, -2, -5])))

10
0
[10 20  0  0]


# 2. Leaky ReLU

This activation function was created to solve the dying ReLU problem using the standard ReLU function that makes the neural network die during training.

![](20241116184355.png)

In [8]:
def leaky_relu(x, alpha = 0.01):
    return np.where(x > 0, x, alpha * x)

# ELU

![](20241116185448.png)

In [9]:
def elu(x, alpha=0.01):
    return np.where(x >= 0, x, alpha * (np.exp(x) - 1))

In [10]:
print(elu(5))

5.0


# Sigmoid

Generate values between 0 to 1

In [17]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [18]:
print(sigmoid(np.array([-1, 0, 1, 2])))

[0.26894142 0.5        0.73105858 0.88079708]


In [23]:
print(sigmoid(0.8))

0.6899744811276125


# Softmax

Suitable for multi-class classification and used mostly in the last layer of a neural network

In [21]:
def softmax(x):
    exp_shifted_x = np.exp(x - np.max(x))
    return exp_shifted_x / np.sum(exp_shifted_x)

In [22]:
print(softmax(np.array([2, 1, .5])))

[0.62853172 0.2312239  0.14024438]
