In [59]:
import numpy as np
import pandas as pd 

In [60]:
df = pd.read_csv('customer.csv')
df.sample(8)

age  gender   review education purchased
28   48    Male     Poor    School        No
4    16  Female  Average        UG        No
34   86    Male  Average    School        No
49   25  Female     Good        UG        No
41   23    Male     Good        PG       Yes
26   53  Female     Poor        PG        No
31   22  Female     Poor    School       Yes
15   75    Male     Poor        UG        No

In [61]:
df_ordinal = df.iloc[:, 2:]
df_ordinal.sample(8)

review education purchased
36     Good        UG       Yes
37  Average        PG       Yes
7      Poor    School       Yes
34  Average    School        No
14     Poor        PG       Yes
17     Poor        UG       Yes
24  Average        PG       Yes
48     Good        UG       Yes

In [62]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_ordinal.iloc[:, 0: 2], df_ordinal.iloc[:, -1], test_size=0.2)

### Ordinal encoding

In [63]:
from sklearn.preprocessing import OrdinalEncoder

In [64]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [65]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [66]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [79]:
X_train

array([[2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [1., 2.]])

In [71]:
X_test

array([[1., 0.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 2.]])

In [72]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

### Label encoding

In [73]:
from sklearn.preprocessing import LabelEncoder

In [74]:
le = LabelEncoder()

In [75]:
le.fit(y_train)

LabelEncoder()

In [76]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [77]:
y_train, y_test

(array([0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1]),
 array([0, 0, 0, 1, 1, 0, 0, 1, 0, 0]))