#### **```NumPy```**

In [2]:
import numpy as np

In [32]:
twoD_array = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(twoD_array)

[[1 2 3 4]
 [5 6 7 8]]


In [33]:
twoD_array.shape

(2, 4)

In [34]:
# check dimensions of an array
print(twoD_array.ndim)

2


In [35]:
# number of elements in an array
print(twoD_array.size)

8


In [36]:
# check data type
print(twoD_array.dtype)

int32


```Convert 2D or multidimensional array into 1D array```

In [55]:
multi_array = np.random.randint(5, 10, (3, 2))
print(multi_array)

# convert into 1D array
single_D_array = multi_array.flatten()
print(single_D_array)

[[6 6]
 [5 5]
 [9 6]]
[6 6 5 5 9 6]


Initial placeholders

In [5]:
# array initialized with all zeros
x = np.zeros((4, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
# array initialized with a particular value
y = np.full((4, 5), 33)
print(y)

[[33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]]


In [23]:
# Identity matrix: matrix that have an equal number of rows and columns 
z = np.eye(6)
print(z)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [24]:
# array with random floating point values
randMatrix1 = np.random.random((5, 6))
print(randMatrix1)

[[0.82831441 0.15674588 0.73284363 0.64878308 0.02846341 0.32305393]
 [0.86957338 0.31947373 0.57893757 0.83959708 0.98452689 0.1037959 ]
 [0.4170586  0.95230876 0.07508509 0.62793439 0.06655223 0.65978389]
 [0.5893525  0.09204255 0.21045216 0.27657333 0.03195808 0.9666506 ]
 [0.81226119 0.12480964 0.91051134 0.86032837 0.56720578 0.45872702]]


In [25]:
# array with random integer values within a specific range
randMatrix2 = np.random.randint(100, 200, (4, 5))
print(randMatrix2)

[[170 151 160 167 145]
 [116 110 111 166 168]
 [123 170 188 113 120]
 [106 128 157 135 107]]


In [26]:
# array with evenly spaced values -> number of values required
evenlySpacedArray = np.linspace(10, 30, 11)
print(evenlySpacedArray)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [27]:
# array with evenly spaced values -> specifying the number of steps
sequenceArray = np.arange(10, 30, 2)
print(sequenceArray)

[10 12 14 16 18 20 22 24 26 28]


In [30]:
# convert regular python list into numpy array
list2 = [10, 20, 30, 40, 50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

#### ```Mathematical operations```

In [41]:
list1 = np.array([1, 2, 3, 4])
list2 = np.array([10, 20, 30, 40])

# concatenation
print(list1 + list2)
print(list1 * list2)

[11 22 33 44]
[ 10  40  90 160]


In [42]:
list2D_1 = np.array([(1, 2, 3), (4, 5, 6)])
list2D_2 = np.array([(10, 20, 30), (40, 50, 60)])
print(list2D_1 + list2D_2)
print(list2D_1 - list2D_2)
print(list2D_1 * list2D_2)
print(list2D_1 / list2D_2)

[[11 22 33]
 [44 55 66]]
[[ -9 -18 -27]
 [-36 -45 -54]]
[[ 10  40  90]
 [160 250 360]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [46]:
a = np.random.randint(10, 20, (3, 3))
b = np.random.randint(30, 40, (3, 3))

In [49]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[49 51 45]
 [50 43 48]
 [53 44 48]]
[[-29 -25 -19]
 [-12 -19 -22]
 [-23 -16 -12]]
[[390 494 416]
 [589 372 455]
 [570 420 540]]
[[0.25641026 0.34210526 0.40625   ]
 [0.61290323 0.38709677 0.37142857]
 [0.39473684 0.46666667 0.6       ]]


In [52]:
# Transpose matrix: A matrix that obtained by interchanging the rows and columns.
matrix = np.random.randint(10, 30, (3, 2))
print(matrix)

# initializing matrix as transpose matrix
transpose_mat = matrix.T
print(transpose_mat)

# converting the existing matrix into a transpose matrix
matrix = matrix.T
print(matrix)

[[15 23]
 [25 29]
 [29 18]]
[[15 25 29]
 [23 29 18]]
[[15 25 29]
 [23 29 18]]


```Reshaping an array```

In [60]:
a = np.random.randint(5, 15, (4, 3))
print(a)
b = a.reshape(3, 4)
print(b)

[[ 7 12 10]
 [11  7  7]
 [ 5  5 13]
 [14 10  7]]
[[ 7 12 10 11]
 [ 7  7  5  5]
 [13 14 10  7]]
