#### **```NumPy```**

In [2]:
import numpy as np

In [7]:
twoD_array = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(twoD_array)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
twoD_array.shape

(2, 4)

Initial placeholders

In [5]:
# array initialized with all zeros
x = np.zeros((4, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
# array initialized with a particular value
y = np.full((4, 5), 33)
print(y)

[[33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]]


In [23]:
# Identity matrix: matrix that have an equal number of rows and columns 
z = np.eye(6)
print(z)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [24]:
# array with random floating point values
randMatrix1 = np.random.random((5, 6))
print(randMatrix1)

[[0.82831441 0.15674588 0.73284363 0.64878308 0.02846341 0.32305393]
 [0.86957338 0.31947373 0.57893757 0.83959708 0.98452689 0.1037959 ]
 [0.4170586  0.95230876 0.07508509 0.62793439 0.06655223 0.65978389]
 [0.5893525  0.09204255 0.21045216 0.27657333 0.03195808 0.9666506 ]
 [0.81226119 0.12480964 0.91051134 0.86032837 0.56720578 0.45872702]]


In [25]:
# array with random integer values within a specific range
randMatrix2 = np.random.randint(100, 200, (4, 5))
print(randMatrix2)

[[170 151 160 167 145]
 [116 110 111 166 168]
 [123 170 188 113 120]
 [106 128 157 135 107]]


In [26]:
# array with evenly spaced values -> number of values required
evenlySpacedArray = np.linspace(10, 30, 11)
print(evenlySpacedArray)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [27]:
# array with evenly spaced values -> specifying the number of steps
sequenceArray = np.arange(10, 30, 2)
print(sequenceArray)

[10 12 14 16 18 20 22 24 26 28]
