#### **```NumPy```**

In [2]:
import numpy as np

In [7]:
twoD_array = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(twoD_array)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
twoD_array.shape

(2, 4)

Initial placeholders

In [5]:
# array initialized with all zeros
x = np.zeros((4, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# array initialized with a particular value
y = np.full((4, 5), 33)
print(y)

In [ ]:
# Identity matrix: matrix that have an equal number of rows and columns 
z = np.eye(6)
print(z)

In [ ]:
# array with random floating point values
randMatrix1 = np.random.random((5, 6))
print(randMatrix1)

In [ ]:
# array with random integer values within a specific range
randMatrix2 = np.random.randint(100, 200, (4, 5))
print(randMatrix2)

In [ ]:
# array with evenly spaced values -> number of values required
evenlySpacedArray = np.linspace(10, 30, 11)
print(evenlySpacedArray)

In [ ]:
# array with evenly spaced values -> specifying the number of steps
sequenceArray = np.arange(10, 30, 2)
print(sequenceArray)