#### **```NumPy```**

In [1]:
import numpy as np

In [2]:
twoD_array = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(twoD_array)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
twoD_array.shape

(2, 4)

In [4]:
# check dimensions of an array
print(twoD_array.ndim)

2


In [5]:
# number of elements in an array
print(twoD_array.size)

8


In [6]:
# check data type
print(twoD_array.dtype)

int64


```Convert 2D or multidimensional array into 1D array```

In [7]:
multi_array = np.random.randint(5, 10, (3, 2))
print(multi_array)

# convert into 1D array
single_D_array = multi_array.flatten()
print(single_D_array)

[[9 6]
 [7 8]
 [7 8]]
[9 6 7 8 7 8]


Initial placeholders

In [8]:
# array initialized with all zeros
x = np.zeros((4, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
# array initialized with a particular value
y = np.full((4, 5), 33)
print(y)

[[33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]
 [33 33 33 33 33]]


In [10]:
# Identity matrix: matrix that have an equal number of rows and columns 
z = np.eye(6)
print(z)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [11]:
# array with random floating point values
randMatrix1 = np.random.random((5, 6))
print(randMatrix1)

[[0.56785416 0.27193852 0.06164816 0.57658489 0.19343946 0.19226107]
 [0.96799658 0.76774287 0.43271139 0.84682594 0.88630867 0.99830563]
 [0.30690988 0.81393493 0.61499979 0.3997269  0.84031393 0.57907104]
 [0.34414071 0.13069238 0.93393454 0.93182439 0.0225516  0.11238463]
 [0.56605133 0.60112594 0.74507762 0.27733109 0.39846746 0.05928209]]


In [12]:
# array with random integer values within a specific range
randMatrix2 = np.random.randint(100, 200, (4, 5))
print(randMatrix2)

[[138 192 113 104 107]
 [100 197 158 149 110]
 [144 110 187 195 194]
 [187 111 114 108 188]]


In [13]:
# array with evenly spaced values -> number of values required
evenlySpacedArray = np.linspace(10, 30, 11)
print(evenlySpacedArray)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [14]:
# array with evenly spaced values -> specifying the number of steps
sequenceArray = np.arange(10, 30, 2)
print(sequenceArray)

[10 12 14 16 18 20 22 24 26 28]


In [15]:
# convert regular python list into numpy array
list2 = [10, 20, 30, 40, 50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

#### ```Mathematical operations```

In [16]:
list1 = np.array([1, 2, 3, 4])
list2 = np.array([10, 20, 30, 40])

# concatenation
print(list1 + list2)
print(list1 * list2)

[11 22 33 44]
[ 10  40  90 160]


In [17]:
list2D_1 = np.array([(1, 2, 3), (4, 5, 6)])
list2D_2 = np.array([(10, 20, 30), (40, 50, 60)])
print(list2D_1 + list2D_2)
print(list2D_1 - list2D_2)
print(list2D_1 * list2D_2)
print(list2D_1 / list2D_2)

[[11 22 33]
 [44 55 66]]
[[ -9 -18 -27]
 [-36 -45 -54]]
[[ 10  40  90]
 [160 250 360]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [18]:
a = np.random.randint(10, 20, (3, 3))
b = np.random.randint(30, 40, (3, 3))

In [19]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[51 45 50]
 [50 50 48]
 [43 47 48]]
[[-13 -21 -14]
 [-20 -20 -16]
 [-21 -17 -24]]
[[608 396 576]
 [525 525 512]
 [352 480 432]]
[[0.59375    0.36363636 0.5625    ]
 [0.42857143 0.42857143 0.5       ]
 [0.34375    0.46875    0.33333333]]


In [20]:
# Transpose matrix: A matrix that obtained by interchanging the rows and columns.
matrix = np.random.randint(10, 30, (3, 2))
print(matrix)

# initializing matrix as transpose matrix
transpose_mat = matrix.T
print(transpose_mat)

# converting the existing matrix into a transpose matrix
matrix = matrix.T
print(matrix)

[[10 29]
 [25 25]
 [21 14]]
[[10 25 21]
 [29 25 14]]
[[10 25 21]
 [29 25 14]]


```Reshaping an array```

In [21]:
a = np.random.randint(5, 15, (4, 3))
print(a)
b = a.reshape(3, 4)
print(b)

[[ 9  8 14]
 [13 12 13]
 [13  5  5]
 [12 11 11]]
[[ 9  8 14 13]
 [12 13 13  5]
 [ 5 12 11 11]]
