Generate array [0 ... 5] using numpy

In [19]:
import numpy as np

In [20]:
generate_array = np.arange(6)
generate_array

array([0, 1, 2, 3, 4, 5])

Generate array of 5 zeros

In [21]:
allZeroes = np.zeros(5)
allZeroes

array([0., 0., 0., 0., 0.])

In [22]:
matrixWithZeros = np.array([(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0)])
matrixWithZeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
matrixWithZeros2 = np.zeros((3, 4))
matrixWithZeros2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

07

In [24]:
builtinOne = np.array([1] * 5)
builtinOne

array([1, 1, 1, 1, 1])

In [25]:
builtin10 = np.array([10] * 5)
builtin10

array([10, 10, 10, 10, 10])

09

In [26]:
evenNumbersInRange = np.arange(50, 100, 2)
evenNumbersInRange

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

In [27]:
# Generate an array of 10 linearly spaced points between 0 and 1

arrayWithFloatingPoints = np.linspace(0, 1, 10)
# arrayWithFloatingPoints
print(arrayWithFloatingPoints)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [28]:
# 11 

# Creating the vector of 25 numbers
number_till_25 = np.arange(0, 25)
number_till_25


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
# now converting into 2D 
number_till_25 = number_till_25.reshape(5, 5)
number_till_25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
# use of shape 
number_till_25.shape

# as we can see, the shape is not a typical function to perform dimensional conversion, rather it only shows the current dimension of the matrix  

(5, 5)

In [31]:
# 12 
matrix_floating = np.matrix(np.linspace(0.1, 2.5, 25).reshape(5, 5))
matrix_floating

matrix([[0.1, 0.2, 0.3, 0.4, 0.5],
        [0.6, 0.7, 0.8, 0.9, 1. ],
        [1.1, 1.2, 1.3, 1.4, 1.5],
        [1.6, 1.7, 1.8, 1.9, 2. ],
        [2.1, 2.2, 2.3, 2.4, 2.5]])

In [32]:
# 13
array = np.matrix(np.linspace(0, 24, 25).reshape(5, 5))
array = array.astype(int)
array

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [33]:
# 14

# linspace: linspace refers to Linearly Spaced Elements which takes a range and generates the evenly spaced floating point values

# arange: arange function is responsible for generating integer values within a range with a default step value 1

In [34]:
# 15 

random_integer = np.random.randint(0, 10)
random_integer

2

In [35]:
# 16 Write a code to generate a 7x5 matrix of 35 random numbers? use rand here
matrix_floating = np.random.rand(7, 5)
matrix_floating

array([[0.61015423, 0.25838403, 0.36730066, 0.88785976, 0.37273609],
       [0.28475963, 0.58048942, 0.0597045 , 0.768963  , 0.28648119],
       [0.39111955, 0.52722784, 0.38671627, 0.99077762, 0.57547569],
       [0.9938352 , 0.57635506, 0.35474375, 0.73934122, 0.48002115],
       [0.37798141, 0.17522518, 0.93017603, 0.23109333, 0.91377059],
       [0.40129314, 0.04766194, 0.27265631, 0.99669029, 0.10035106],
       [0.3488354 , 0.2033765 , 0.33659501, 0.71842437, 0.8287015 ]])

In [36]:
# 17
identity_matrix = np.identity(5)
np.fill_diagonal(identity_matrix, 5)
identity_matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])