Generate array [0 ... 5] using numpy

In [79]:
import numpy as np

In [80]:
generate_array = np.arange(6)
generate_array

array([0, 1, 2, 3, 4, 5])

Generate array of 5 zeros

In [81]:
allZeroes = np.zeros(5)
allZeroes

array([0., 0., 0., 0., 0.])

In [82]:
matrixWithZeros = np.array([(0, 0, 0, 0), (0, 0, 0, 0), (0, 0, 0, 0)])
matrixWithZeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [83]:
matrixWithZeros2 = np.zeros((3, 4))
matrixWithZeros2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

07

In [84]:
builtinOne = np.array([1] * 5)
builtinOne

array([1, 1, 1, 1, 1])

In [85]:
builtin10 = np.array([10] * 5)
builtin10

array([10, 10, 10, 10, 10])

09

In [86]:
evenNumbersInRange = np.arange(50, 100, 2)
evenNumbersInRange

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

In [87]:
# Generate an array of 10 linearly spaced points between 0 and 1

arrayWithFloatingPoints = np.linspace(0, 1, 10)
# arrayWithFloatingPoints
print(arrayWithFloatingPoints)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [88]:
# 11 

# Creating the vector of 25 numbers
number_till_25 = np.arange(0, 25)
number_till_25


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [89]:
# now converting into 2D 
number_till_25 = number_till_25.reshape(5, 5)
number_till_25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
# use of shape 
number_till_25.shape

# as we can see, the shape is not a typical function to perform dimensional conversion, rather it only shows the current dimension of the matrix  

(5, 5)

In [91]:
# 12 
matrix_floating = np.matrix(np.linspace(0.1, 2.5, 25).reshape(5, 5))
matrix_floating

matrix([[0.1, 0.2, 0.3, 0.4, 0.5],
        [0.6, 0.7, 0.8, 0.9, 1. ],
        [1.1, 1.2, 1.3, 1.4, 1.5],
        [1.6, 1.7, 1.8, 1.9, 2. ],
        [2.1, 2.2, 2.3, 2.4, 2.5]])

In [92]:
# 13
array = np.matrix(np.linspace(0, 24, 25).reshape(5, 5))
array = array.astype(int)
array

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [93]:
# 14

# linspace: linspace refers to Linearly Spaced Elements which takes a range and generates the evenly spaced floating point values

# arange: arange function is responsible for generating integer values within a range with a default step value 1

In [94]:
# 15 

random_integer = np.random.randint(0, 10)
random_integer

7

In [95]:
# 16 Write a code to generate a 7x5 matrix of 35 random numbers? use rand here
matrix_floating = np.random.rand(7, 5)
matrix_floating

array([[0.9988964 , 0.76244562, 0.05792891, 0.64044223, 0.39766437],
       [0.71191776, 0.17505661, 0.71430692, 0.00301362, 0.45928619],
       [0.51990725, 0.65507206, 0.86706158, 0.94393037, 0.88125072],
       [0.84971757, 0.13130811, 0.70559108, 0.72873982, 0.52354997],
       [0.28155679, 0.93761785, 0.92569597, 0.11811456, 0.69498394],
       [0.49070347, 0.77012248, 0.19938984, 0.15475125, 0.80109734],
       [0.98260605, 0.55550817, 0.38545312, 0.31895332, 0.7296293 ]])

In [96]:
# 17
identity_matrix = np.identity(5)
np.fill_diagonal(identity_matrix, 5)
identity_matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])